### ISSUE TITLE
Unexpected error message "You don't have access to Analytify Dashboard"

### ISSUE THREAD

**Issue by fredzj** [Analytify/wp-analytify#42]
As Administrator, I have added all roles to [Show Analytics to roles 
( posts & pages )] in page /wp-admin/admin.php?page=analytify-settings.

As Editor, I get the error message "You don't have access to Analytify Dashboard" in page /wp-admin/admin.php?page=analytify-dashboard.

**Comment by burhandodhy** [comment]
Are you using Analytify Pro ?

**Comment by fredzj** [comment]
No, it's the free versio:

Analytify - Google Analytics Dashboard Version: 2.1.15
Analytify - Gooogle Analytics Dashboard widget Version 1.0.7

**Comment by sublines** [comment]
I have the same problem.

**Comment by burhandodhy** [comment]
In our free version, Only Admins can access the Analytify dashboard stats. Pro version has Dashboard tab for its settings. Here is the “Dashboard Tab” screenshot http://prntscr.com/expffj

Free version configuration for Admin tab is for stats under posts not for Analytify dashboard.

**Comment by nesoor** [comment]
> In our free version, Only Admins can access the Analytify dashboard stats. Pro version has Dashboard tab for its settings. Here is the “Dashboard Tab” screenshot http://prntscr.com/expffj
> 
> Free version configuration for Admin tab is for stats under posts not for Analytify dashboard.

Oh wow, no offence but I was testing Analyitfy and I WAS interested in the pro version but no BASIC statistics for none pro user is something that already stops me from using it.
Not all my customers are interested in the pro version but they are interested in BASIC SEO statistics.
I am not going to use two types of software just because Analyitfy doesn't show statistics to other user roles. That's my opinion, sorry.
