### ISSUE TITLE
No possiblity to connect with GA 

### ISSUE THREAD

**Issue by RobertPiotrowskiPro** [Analytify/wp-analytify#51]
Hi,

There is a small issue:

I have connected the Analytify plugin with GA, before creating the account for a new website in GA.
I have created the account in GA and it was not possible to choose the new website as it has not been on the list.

The solution:
log out and sign in once again.

**Comment by YonatanKra** [comment]
I tried that - but it did not solve the issue. Any other solution?

**Comment by hiddenpearls** [comment]
@RobertPiotrowskiPro @YonatanKra 

The reason is - You are using the new GA4 property and Google Analytics doesn't support the APIs yet. So please check the https://analytify.io/doc/how-to-integrate-analytify-with-google-analytics-4-ga4/ article and see how you can use Analytify with new Property.

Note: We recommend connecting GA4 and UA to each other and use both Tracking reports. UA can be viewed in Analytify while GA4 is only available in Google Analytics.
